tencent:
  auth:
#企业微信的corpid
    corpid: "ww97af1eab5d2add3c"
#企业微信的corpxecret
    corpsecret: "iq2IyxRcY3oCHHTFg2U2o3UQGHzXIWkKIAgfKQFdhxw"
# 应用的agentid
  agentid: "1000002"
  businesstype:
    CRM:
      - ralap
    SSM:
      - test
    DLM:
      - myzone
#      vx:

  user:
#接受告警的用户配置，可配置多个
    - ZhuRongJia
#webhook监听端口
listenport: "9000"